#!/usr/bin/env bash
set -euo pipefail

if [ -t 0 ]; then
  echo "warning: stdin is terminal" >&2
fi

if [ ! -f "$1" ] || [ "$1" = "${1%.hs}" ]; then
  echo "not a source file: $1" >&2
  exit 1
fi

stack ghc "$1"
"${1%.hs}"
